export { default as Logo } from './Logo/Logo'
export { default as Footer } from './Footer/Footer'
export { default as PageTitle } from './PageTitle/PageTitle'
export { default as PageHero } from './PageHero/PageHero'
export { default as Main } from './Main/Main'
export { default as RegistryCard } from './RegistryCard/RegistryCard'